### PR TITLE
engine 9

### PR DESCRIPTION
**Pull request by tanner0101**
Includes updates to hashing and encryption.

### CODE REVIEW

**Comment by edjiang** [comment]
@tannernelson any specific changes to encryption that could be causing this to fail? Looks like we're not able to do FB login anymore. Haven't tried it myself yet

**Comment by edjiang** [comment]
I remember last time we used a temp HTTP client that doesn't validate the SSL Cert (until I update this to Foundation, which is pending some bug fixes in it (or I just do more workarounds))

Could that be now failing the test?

Temp HTTP Client: https://github.com/stormpath/Turnstile/blob/master/Sources/TurnstileWeb/TempHTTPClient.swift

Foundation bug: https://bugs.swift.org/browse/SR-2570

**Comment by tanner0101** [comment]
Only thing that changed there is we're sending a user agent now. Maybe facebook doesn't like that? I re-ran the tests in case something was just up with their servers.

**Comment by edjiang** [comment]
I realized what went wrong. You issued this pull request from an external repo, which Travis then doesn't use the secret environment variables for. This is so a malicious user can't print them out / etc to steal them, just by issuing a pull request.

This caused the build to fail. 

You have commit privileges on this repo, so next time you should create a branch =] I've cherry-picked your first commit and put it in master. I think it should pass and then we'll be able to tag.

**Pull request closed without merging**
