### PR TITLE
Add docs for Digits

### PR DESCRIPTION
**Pull request by kdawgwilk**
I tried to keep things as loosely tied to Vapor as possible when explaining it but I wasn't even thinking outside of the Vapor framework as I implemented it so if there are things that need to change I would be happy to submit another PR

### CODE REVIEW

**Comment by edjiang** [comment]
This looks great! 

Two things we should investigate, though:

1. You mention Twitter in the README. We should create a dedicated Twitter realm, then, or remove mention for now. 
2. Yes, the code is Vapor-specific =] Since the frameworks are all a bit different, I'd recommend outlining the general steps that the auth flow takes, and the developer action that is needed.

I can revise this too, if you'd like!

**Comment by kdawgwilk** [comment]
I am not sure what the future of Digits is going to be after the [Google acquisition of Fabric tools](http://get.digits.com/blog/digits-fabric-google).  Is this still worth including into Turnstile?

**Comment by edjiang** [comment]
I'm fairly confident it will be rolled into Firebase Auth at worst; if that's the case it might switch to an OAuth 2 API with the OAuth 1.0a version deprecated. I'm not worried right now!

**Comment by edjiang** [comment]
Sorry this has taken so long; we should get the stuff merged. I'm busy for the next two weeks, but can start working on this again after then =]

**Comment by kdawgwilk** [comment]
I am going to have some time this weekend to get some of this moving forward.  I haven't been working with my Vapor stuff much since I finished my iOS class last semester but I really want to get back and finish things up that I had started, including this.

**Comment by kdawgwilk** [comment]
I removed the mentions of Twitter since that integration has not been created yet and will add it back in once that happens.  This should be good to merge

**Comment by edjiang** [comment]
Awesome. I still have merge power, but just FYI I am no longer working for Stormpath. There's one more mention of Twitter that I'll remove, but let me double check with @omgitstom that it's OK for me to touch this repo :)

**Pull request merged**
